[project]
name = "emulat3"
version = "0.1.0"
description = "Step through PE functions or shellcode instruction-by-instruction (amd64)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=11.0.0",
    "viv-utils>=0.7.0",
    "vivisect>=1.1.0",
    "pytest>=7.0.0",
    "mockito>=1.2.0",
]
